### ISSUE TITLE
Re-ordering team members in team area only works after refresh

### ISSUE THREAD

**Issue by triinjassov** [Teamweek/teamweek#1008] opened 2015-09-02 10:28 UTC
From the user:

Unfortunately I wasn't able to reproduce it on Mac,Yosemite, latest Chrome

Here are the info on my system:

- Windows 8.1
- Chrome (Version 44.0.2403.157 m)
- Firefox (Version 39.0.3)

With both browser, I have following behavior:
- I try to change the order in which the team members are displayed (drag
and drop)
- they systematically come back to the original order
- if I close the current tab and then reopen my teamweek timeline, then I
can see the change is taken into account and the team members are
displayed in the order I wanted.

This is definitely not a major issue as I won't change the order of the
team members everyday but I thought this could be a useful feedback for you

**Comment by triinjassov** [comment] 2015-09-02 10:28
case 187837

**Comment by herkyl** [comment] 2015-09-02 10:40
Duplicate of https://github.com/Teamweek/teamweek/issues/965

**Closed by herkyl** 2015-09-02 10:40 UTC
